### ISSUE TITLE
Relative URL without a Base

### ISSUE THREAD

**Issue by kobear403** [LukeChannings/moviematch#41]
_Originally posted by @LukeChannings in https://github.com/LukeChannings/moviematch/issues/8#issuecomment-742462840_

I followed some of the steps in issue #8, my issue is as follows

error: Uncaught (in promise) URIError: relative URL without a base
    at processResponse (deno:core/core.js:223:11)
    at Object.jsonOpAsync (deno:core/core.js:240:12)
    at async fetch (deno:op_crates/fetch/26_fetch.js:1278:29)
    at async getSections (plex.ts:30:15)
    at async plex.ts:74:20

I confirmed `<PLEX_URL>/library/sections?X-Plex-Token=<PLEX_TOKEN>` in a browser it does load some XML and not give an Unauthorized error. My <PLEX_URL> is `http://127.0.0.1:32400`

I obtained the token by right clicking the Plex server icon on my PC, and then using the find XML guide referenced in the readme

**Comment by kobear403** [comment]
I'm a n00b who hasn't coded in a long time and my <PLEX_URL> was <http://127.0.0.1:3240> instead of "http://127.0.0.1:3240"
